;BEGIN FRAGMENT CODE - Do not edit anything between this and the end comment
;NEXT FRAGMENT INDEX 2
Scriptname QF_CWCitizensFlee_0006434A Extends Quest Hidden

;BEGIN ALIAS PROPERTY Citizen16
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen16 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen6
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen6 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen58
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen58 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen56
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen56 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen38
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen38 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen18
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen18 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen73
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen73 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen53
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen53 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen3
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen3 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen13
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen13 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen19
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen19 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen57
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen57 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen9
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen9 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen37
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen37 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen59
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen59 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen17
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen17 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen12
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen12 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen2
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen2 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen52
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen52 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen72
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen72 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen1
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen1 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen11
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen11 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen71
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen71 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen51
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen51 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen54
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen54 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen74
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen74 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen14
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen14 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen4
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen4 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen50
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen50 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen70
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen70 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen10
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen10 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen30
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen30 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen35
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen35 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen15
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen15 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen75
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen75 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen55
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen55 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen68
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen68 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen48
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen48 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen26
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen26 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen28
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen28 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen46
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen46 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen66
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen66 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen63
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen63 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen43
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen43 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen23
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen23 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen67
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen67 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen29
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen29 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen47
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen47 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen49
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen49 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen27
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen27 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen69
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen69 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen22
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen22 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen42
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen42 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen62
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen62 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen21
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen21 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen61
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen61 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen41
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen41 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen44
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen44 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen64
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen64 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Location
;ALIAS PROPERTY TYPE LocationAlias
LocationAlias Property Alias_Location Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen24
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen24 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen40
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen40 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen60
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen60 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen31
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen31 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen7
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen7 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen32
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen32 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen20
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen20 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen39
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen39 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen36
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen36 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen25
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen25 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen5
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen5 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen34
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen34 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen33
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen33 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen65
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen65 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen8
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen8 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Citizen45
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Citizen45 Auto
;END ALIAS PROPERTY

;BEGIN FRAGMENT Fragment_1
Function Fragment_1()
;BEGIN CODE
; CWScript.Log("CWCitizensFlee ", "CWCitizensFlee stage 255, shutdown stage")
;END CODE
EndFunction
;END FRAGMENT

;BEGIN FRAGMENT Fragment_0
Function Fragment_0()
;BEGIN CODE
;WHATEVER STARTS THIS QUEST NEEDS TO BE SURE TO STOP IT
; CWScript.Log("CWCitizensFlee ", "CWCitizensFlee stage 0, startup stage")
;END CODE
EndFunction
;END FRAGMENT

;END FRAGMENT CODE - Do not edit anything between this and the begin comment
