;BEGIN FRAGMENT CODE - Do not edit anything between this and the end comment
;NEXT FRAGMENT INDEX 2
Scriptname QF_CWSiegeAttackObj_0004E857 Extends Quest Hidden

;BEGIN ALIAS PROPERTY Obj01
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Obj01 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY CityGate
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_CityGate Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Archer02
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Archer02 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Jarl
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Jarl Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY General
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_General Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY SecondGateLever
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_SecondGateLever Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Archer03
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Archer03 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY FirstGateLever
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_FirstGateLever Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Obj02
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Obj02 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY City
;ALIAS PROPERTY TYPE LocationAlias
LocationAlias Property Alias_City Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Obj03
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Obj03 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Obj04
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Obj04 Auto
;END ALIAS PROPERTY

;BEGIN ALIAS PROPERTY Archer01
;ALIAS PROPERTY TYPE REFERENCEALIAS
REFERENCEALIAS Property Alias_Archer01 Auto
;END ALIAS PROPERTY

;BEGIN FRAGMENT Fragment_1
Function Fragment_1()
;BEGIN CODE
;Success
stop()
;END CODE
EndFunction
;END FRAGMENT

;BEGIN FRAGMENT Fragment_0
Function Fragment_0()
;BEGIN CODE
;FAILED
stop()
;END CODE
EndFunction
;END FRAGMENT

;END FRAGMENT CODE - Do not edit anything between this and the begin comment
