Scriptname TGRLootHandlerQuestScript extends Quest  Conditional

GlobalVariable Property pLoot01 Auto Conditional
GlobalVariable Property pLoot02 Auto Conditional
GlobalVariable Property pLoot03 Auto Conditional
Quest Property pTGRLootHandlerQuest Auto Conditional