Scriptname WIChangeLocation05 extends WorldInteractionsScript  Conditional
{Extends WorldInteractionsScript}

LeveledItem Property WIChangeLocation05GiftAdult Auto
LeveledItem Property WIChangeLocation05GiftChild Auto

